### ISSUE TITLE
Crashes on FreeBSD with SEGV

### ISSUE THREAD

**Issue by yurivict** [salsaman/LiVES#27]
Version 3.2.0 SEGVs on FreeBSD 12.2.

Stack trace:
```

$ lives -debug

LiVES 3.2.0
Copyright 2002 - 2020 Gabriel Finch (salsaman+lives@gmail.com) and others.
LiVES comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details.

grep: /proc/stat: No such file or directory

Unfortunately LiVES crashed.
Please report this bug at https://github.com/salsaman/LiVES/issues
Thanks. Recovery should be possible if you restart LiVES.


When reporting crashes, please include details of your operating system, distribution, and the LiVES version (3.2.0)
and any information shown below:

lives-exe (pid:11194): [E]xit, [H]alt, show [S]tack trace or [P]roceed: S
#0  _wait4 () at _wait4.S:3
#1  0x00000008013adf7c in __thr_wait4
#2  0x000000080194df7c in g_on_error_stack_trace ()
#3  0x000000080194dd6e in g_on_error_query ()
#4  0x000000000028ff49 in  ()
#5  0x00000008013b0c60 in handle_signal
#6  0x00000008013b022f in thr_sighandler
#7  0x00007ffffffff003 in <signal handler called> ()
#8  0x0000000856c9512e in dv_decoder_free () at /usr/local/lib/libdv.so.4
#9  0x00000008527f3a76 in clip_data_free ()
#10 0x00000008527f39c1 in get_clip_data ()
#11 0x00000000002b7772 in  ()
#12 0x0000000000364e63 in  ()
#13 0x00000000003d3415 in  ()
#14 0x00000008013f3ced in g_closure_invoke ()
#15 0x0000000801409602 in  () at /usr/local/lib/libgobject-2.0.so.0
#16 0x000000080140a45b in g_signal_emit_valist ()
#17 0x000000080140ab16 in g_signal_emit ()
#18 0x0000000800d381d7 in gtk_widget_activate ()
#19 0x0000000800be7bf8 in gtk_menu_shell_activate_item ()
#20 0x0000000800be95c8 in  () at /usr/local/lib/libgtk-3.so.0
#21 0x0000000800d8a614 in  () at /usr/local/lib/libgtk-3.so.0
#22 0x00000008013f3ed6 in  () at /usr/local/lib/libgobject-2.0.so.0
#23 0x000000080140a13f in g_signal_emit_valist ()
#24 0x000000080140ab16 in g_signal_emit ()
#25 0x0000000800d37a0c in  () at /usr/local/lib/libgtk-3.so.0
#26 0x0000000800bd2fff in gtk_propagate_event ()
#27 0x0000000800bd2b8d in gtk_main_do_event () at /usr/local/lib/libgtk-3.so.0
#28 0x0000000801151a11 in  () at /usr/local/lib/libgdk-3.so.0
#29 0x0000000801187097 in  () at /usr/local/lib/libgdk-3.so.0
#30 0x0000000801982487 in g_main_context_dispatch ()
#31 0x000000080198284a in  () at /usr/local/lib/libglib-2.0.so.0
#32 0x0000000801982b8f in g_main_loop_run () at /usr/local/lib/libglib-2.0.so.0
#33 0x0000000800bd249b in gtk_main () at /usr/local/lib/libgtk-3.so.0
#34 0x00000000002989e8 in  ()
#35 0x000000000029df7b in  ()
#36 0x0000000000272bc0 in  ()
#37 0x00000008004d5000 in  ()
#38 0x0000000000000000 in  ()
lives-exe (pid:11194): [E]xit, [H]alt, show [S]tack trace or [P]roceed:
```

Downstream bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253495

**Comment by salsaman** [comment]
Thanks. This matter was brought to my attention just minutes ago, and I have responded on bugzilla. I suggest that we close the issue here and use the bugzilla report instead.
